### ISSUE TITLE
Missing firmware and SPLD images

### ISSUE THREAD

**Issue by hfvermeer** [rreilink/xtsd#1]
I am interested in building this project, but the repository does not contain the associated firmware or SPLD images. Is there any way that you could include them?

**Comment by rreilink** [comment]
Good point, thanks for finding this. 

I've added the SPLD source and JEDEC binary. I've used [afterburner](https://github.com/ole00/afterburner) to program it.  For the Flash memory firmware source, binary and associated tools, I need to get this off my old XT PC since that's where I did the development, and that does not have git on it ;-). I haven't been working on this for quite a while though, so I'll need to see whether it still boots at all. Please bear with me and stay tuned.

**Comment by hfvermeer** [comment]
I sure will. I happened to have an order in production at JLC and I managed to squeeze one more item in. So no pressure ;-).
